In [1]:
import numpy as np

In [2]:
array = np.random.randint(-10, 10, size=9)
print(f"{array = }")

print(
    f"sum: {np.sum(array)};",
    f"prod: {np.prod(array)};",
    f"cumulative sum: {np.cumsum(array)};",
    f"cumulative prod:\n{np.cumprod(array)}",
    sep="\n",
)

array = array([  2, -10,  -9,  -9,  -9,   6,   0,   9,  -7])
sum: -27;
prod: 0;
cumulative sum: [  2  -8 -17 -26 -35 -29 -29 -20 -27];
cumulative prod:
[    2   -20   180 -1620 14580 87480     0     0     0]


In [3]:
array = np.random.randint(-10, 10, size=9)
print(f"{array = }")

print(
    f"min: {np.min(array)};",
    f"max: {array.max()};",
    f"mean: {np.mean(array)};",
    f"median: {np.median(array)};",
    f"std: {np.std(array)};",
    f"variance: {np.var(array)};",
    sep="\n",
)

array = array([ 1,  2, -5,  4, -3, -4, -2,  9,  7])
min: -5;
max: 9;
mean: 1.0;
median: 1.0;
std: 4.666666666666667;
variance: 21.77777777777778;


In [3]:
def pad_image(image: np.ndarray, pad_size: int) -> np.ndarray:

    if pad_size < 1:
        raise ValueError

    if image.ndim == 2:
        padded = np.zeros(np.array(image.shape) + 2 * pad_size, dtype=np.uint8)

    if image.ndim == 3:
        padded = np.zeros(
            (image.shape[0] + 2 * pad_size, image.shape[1] + 2 * pad_size, image.shape[2]),
            dtype=np.uint8,
        )

    padded[pad_size : padded.shape[0] - pad_size, pad_size : padded.shape[1] - pad_size] = image

    return padded

In [37]:
arr1 = np.array([[1, 2]], dtype=np.uint8)
arr2 = pad_image(arr1, 1)
arr2

array([[0, 0, 0, 0],
       [0, 1, 2, 0],
       [0, 0, 0, 0]], dtype=uint8)

In [2]:
array = np.random.randint(-10, 10, size=(3, 4))
print(f"array:\n{array}", end="\n\n")

print(
    f"sum: {np.sum(array)};",
    f"cumulative sum: {np.cumsum(array)};",
    f"max: {np.max(array)};",
    sep="\n",
)

array:
[[  8   4   9  -2]
 [  4 -10 -10   4]
 [  7   0   8  -1]]

sum: 21;
cumulative sum: [ 8 12 21 19 23 13  3  7 14 14 22 21];
max: 9;


In [4]:
array = np.random.randint(-10, 10, size=(3, 4))
print(f"array:\n{array}", end="\n\n")

print(
    f"sum whole: {np.sum(array)};",
    f"sum per column: {np.sum(array, axis=0)};",
    f"sum per row: {np.sum(array, axis=1)};",
    sep="\n",
)


print(f"sum per column: {np.sum(array, axis=0, keepdims=True)};")

array:
[[ -4   1  -8  -9]
 [ -6   3   7   7]
 [ -2  -4 -10 -10]]

sum whole: -35;
sum per column: [-12   0 -11 -12];
sum per row: [-20  11 -26];
sum per column: [[-12   0 -11 -12]];


In [5]:
array = np.random.randint(-10, 10, size=(2, 3, 2))
print(f"array:\n{array};", end="\n\n")

print(
    f"axis negative:\n{np.sum(array, axis=-2)}",
    f"axis tuple:\n{np.sum(array, axis=(0, 2))}",
    f"axis tuple keepdim:\n{np.sum(array, axis=(0, 2), keepdims=True)}",
    sep="\n\n",
)

array:
[[[-1  9]
  [ 0  7]
  [ 7  7]]

 [[-6  6]
  [ 8  7]
  [-8  3]]];

axis negative:
[[ 6 23]
 [-6 16]]

axis tuple:
[ 8 22  9]

axis tuple keepdim:
[[[ 8]
  [22]
  [ 9]]]


In [6]:
def blur_image(
    image: np.ndarray,
    kernel_size: int,
) -> np.ndarray:

    if kernel_size < 1 or kernel_size % 2 == 0:
        raise ValueError

    print(f"0: \n{image}\n")
    padded = pad_image(image, kernel_size // 2 + 1)
    print(f"1: \n{padded}\n")
    column_cumsum = np.cumsum(padded, axis=0, dtype=np.uint64)
    print(f"2: \n{column_cumsum}\n")
    block_column_sum = (
        column_cumsum[kernel_size : column_cumsum.shape[0] - 1]
        - column_cumsum[: column_cumsum.shape[0] - kernel_size - 1]
    )
    print(f"3: \n{block_column_sum}\n")
    block_cumsum = np.cumsum(block_column_sum, axis=1, dtype=np.uint64)
    print(f"4: \n{block_cumsum}\n")
    block_cumsum[:, kernel_size : block_cumsum.shape[1] - 1] -= block_cumsum[
        :, : block_cumsum.shape[1] - kernel_size - 1
    ]
    print(f"5: \n{block_cumsum}\n")
    blur = block_cumsum[:, kernel_size : block_cumsum.shape[1] - 1] // kernel_size**2

    return blur

In [7]:
arr = np.array(
    [
        [100, 100],
        [100, 100],
    ]
)

blur_image(arr, 3)

0: 
[[100 100]
 [100 100]]

1: 
[[  0   0   0   0   0   0]
 [  0   0   0   0   0   0]
 [  0   0 100 100   0   0]
 [  0   0 100 100   0   0]
 [  0   0   0   0   0   0]
 [  0   0   0   0   0   0]]

2: 
[[  0   0   0   0   0   0]
 [  0   0   0   0   0   0]
 [  0   0 100 100   0   0]
 [  0   0 200 200   0   0]
 [  0   0 200 200   0   0]
 [  0   0 200 200   0   0]]

3: 
[[  0   0 200 200   0   0]
 [  0   0 200 200   0   0]]

4: 
[[  0   0 200 400 400 400]
 [  0   0 200 400 400 400]]

5: 
[[  0   0 200 400 400 400]
 [  0   0 200 400 400 400]]



array([[44, 44],
       [44, 44]], dtype=uint64)

In [ ]:
import numpy as np


def get_dominant_color_info(
    image: np.ndarray[np.uint8],
    threshold: int = 5,
) -> tuple[np.uint8, float]:

    if threshold < 1:
        raise ValueError("threshold must be positive")

    color = np.arange(256, dtype=np.uint8)
    color = color[:, np.newaxis]
    color = color[:, :, np.newaxis]

    image = image[np.newaxis, :, :]

    cnt = image == color
    cnt = np.sum(np.sum(cnt, axis=1), axis=1)
    ans = np.zeros(2 * (threshold + 1) + cnt.shape[0])
    ans[threshold + 1 : ans.shape[0] - threshold - 1] = cnt
    ans = np.cumsum(ans)
    ans = ans[2 * threshold + 1 : ans.shape[0] - 1] - ans[: ans.shape[0] - 1 - 2 * threshold - 1]

    index = np.arange(256, dtype=np.uint8)
    mx = np.max(ans * (cnt != 0))
    ans1 = ((mx == ans) & (cnt != 0)) * index + ((mx != ans) | (cnt == 0)) * -1
    wide = max(cnt * (index == ans1))
    ans1 = ans1 * ((ans1 != -1) & (cnt[ans1] == wide)) + -1 * ((ans1 == -1) | (cnt[ans1] != wide))
    ans2 = np.sum(cnt * ((cnt != 0) & (ans1 != -1))) / sum(cnt)
    ans1 = ans1[ans1 != -1]

    return ans1[0].astype(np.uint8), ans2

In [151]:
get_dominant_color_info(np.array([[0, 100, 200]], dtype=np.uint8), 10)

[  0  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1
  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1
  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1
  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1
  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1
  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1 100  -1  -1  -1  -1  -1  -1  -1
  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1
  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1
  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1
  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1
  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1
  -1  -1 200  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1
  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1
  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -

(np.uint8(0), np.float64(1.0))

In [12]:
costs = np.array(
    [[1.0, 0.0, 1.0], [0.0, 1.0, 1.0]]
)

demand_expected = np.array([1, 1, 1])

costs *= demand_expected
print(costs)
costs = np.sum(costs, axis=1)
resource = np.array([3.0, 3.0])
print(costs)

[[1. 0. 1.]
 [0. 1. 1.]]
[2. 2.]


In [64]:
matrix = np.array([
    [2.0, 0],
    [0, 3.0]
])
vector = np.array([1.0, 2.0])

print(((matrix @ vector) / np.linalg.norm(matrix, axis=1))[:, np.newaxis] * (matrix / (np.linalg.norm(matrix, axis=1))[:, np.newaxis]))

[[1. 0.]
 [0. 2.]]


In [67]:
conjugate = np.array([1, -1] * (2 * 3))
conjugate.reshape(3, 2, 2)
conjugate

array([ 1, -1,  1, -1,  1, -1,  1, -1,  1, -1,  1, -1])